on:
  push:
    tags:
      - "v*"
      # version tag should be like v1.2.3
  workflow_dispatch:

name: Publish Crate

jobs:
  publish:
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install Rust targets
        run: rustup target add riscv64imac-unknown-none-elf
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
